/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as NonTermsRouteImport } from './routes/non-terms'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSignalStreamRouteImport } from './routes/api/signal/stream'

const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const NonTermsRoute = NonTermsRouteImport.update({
  id: '/non-terms',
  path: '/non-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalStreamRoute = ApiSignalStreamRouteImport.update({
  id: '/api/signal/stream',
  path: '/api/signal/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/compliance': typeof ComplianceRoute
  '/mission-control': typeof MissionControlRoute
  '/non-terms': typeof NonTermsRoute
  '/signal': typeof SignalRoute
  '/api/signal/stream': typeof ApiSignalStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/compliance': typeof ComplianceRoute
  '/mission-control': typeof MissionControlRoute
  '/non-terms': typeof NonTermsRoute
  '/signal': typeof SignalRoute
  '/api/signal/stream': typeof ApiSignalStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/compliance': typeof ComplianceRoute
  '/mission-control': typeof MissionControlRoute
  '/non-terms': typeof NonTermsRoute
  '/signal': typeof SignalRoute
  '/api/signal/stream': typeof ApiSignalStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/compliance'
    | '/mission-control'
    | '/non-terms'
    | '/signal'
    | '/api/signal/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/compliance'
    | '/mission-control'
    | '/non-terms'
    | '/signal'
    | '/api/signal/stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/compliance'
    | '/mission-control'
    | '/non-terms'
    | '/signal'
    | '/api/signal/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  ComplianceRoute: typeof ComplianceRoute
  MissionControlRoute: typeof MissionControlRoute
  NonTermsRoute: typeof NonTermsRoute
  SignalRoute: typeof SignalRoute
  ApiSignalStreamRoute: typeof ApiSignalStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-terms': {
      id: '/non-terms'
      path: '/non-terms'
      fullPath: '/non-terms'
      preLoaderRoute: typeof NonTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signal/stream': {
      id: '/api/signal/stream'
      path: '/api/signal/stream'
      fullPath: '/api/signal/stream'
      preLoaderRoute: typeof ApiSignalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  ComplianceRoute: ComplianceRoute,
  MissionControlRoute: MissionControlRoute,
  NonTermsRoute: NonTermsRoute,
  SignalRoute: SignalRoute,
  ApiSignalStreamRoute: ApiSignalStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
